---

# Set up a remote Debian Jessie server 
# Run me with: ansible-playbook -vv -i "<hostname>," jessie.yml

- hosts: all
  remote_user: root
  roles:
    - common
  vars_files:
    - vars.yml

# continue config as nonprivileged user:
- hosts: all
  roles:
    - keysetup
    - dotfiles
    - git
  vars_files:
    - vars.yml

- hosts: all
  sudo: yes
  roles:
    - python
  vars_files:
    - vars.yml
