---

# Set up a remote Debian Jessie server for OpenStack dev
# Pre-requisite: run jessie.yml playbook first.
#
# Run me with: ansible-playbook -vv -i "<hostname>," nova.yml
- hosts: all
  tasks:
    - git: repo=git@github.com:openstack/nova.git
           dest="~/nova"

    - name: install pre-reqs that nova wants
      apt: name="{{ item }}" state=present
      sudo: yes
      with_items:
        - libffi-dev
        - libmysqlclient-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - openssl
        - libpq-dev

    - set_fact: home="{{ ansible_user_dir }}"

    - name: install nova into venv
      pip: chdir="{{ home }}/nova"
           extra_args="-e ."
           requirements="requirements.txt"
           virtualenv="{{ home }}/venv/nova"

    - pip: name=MySQL-python state=present
           virtualenv="{{ home }}/venv/nova"
