---

# Set up a remote cloud server
# Run me with: ansible-playbook -vv -i "<hostname>," server.yml
#
# Tested on Ubuntu 16.04 LTS with Ansible 2.5.3
#
- hosts: all
  remote_user: root
  roles:
    - common
  vars_files:
    - vars.yml

# continue config as nonprivileged user:
- hosts: all
  remote_user: "{{ remote_username }}"
  roles:
    - keysetup
    - dotfiles
    - git
  vars_files:
    - vars.yml

- hosts: all
  become: yes
  roles:
    - python
  vars_files:
    - vars.yml
