---

- file: path="{{ ansible_env.HOME }}/.ssh"
        state=directory
        mode=0700

- name: authorize personal key
  copy: src="{{ local_home }}/.ssh/id_rsa.pub"
        dest="{{ ansible_env.HOME }}/.ssh/authorized_keys"
        mode=0644
