---

- name: set hostname
  hostname: name={{ ansible_hostname }}

- name: get aptitude so upgrade will work
  apt: update_cache=yes name=aptitude

- name: apt upgrade
  apt: "upgrade={{ apt_upgrade_type }} update_cache=no"

- name: apt install common packages
  apt: name={{ item }} state=present
  loop: "{{ packages }}"

- name: create nonprivileged user
  user: name="{{ remote_username }}" shell="/bin/bash"

- name: add authorized key to user
  authorized_key: user="{{ remote_username }}"
                  key="{{ pubkey }}"

- name: give user sudo power
  template: src="sudoers.j2"
            dest="/etc/sudoers.d/sudoers"
            mode=0440 owner=root group=root

- name: Reboot system if required
  shell: sleep 5 && shutdown -r now 'Rebooting to complete system upgrade'
         removes=/var/run/reboot-required
  async: 1
  poll: 0
  ignore_errors: yes
  register: restarted

- name: Wait for SSH accessibility
  wait_for_connection:
    connect_timeout: 15
  when: restarted.changed
